In [56]:
# import
import pandas as pd
import seaborn as sns

In [ ]:
# load raw data
raw = pd.read_csv("/work/E2026/psycholing_kma/data/combined_data.csv")
raw.head(20)

,participant_id,component_num,url,meta,sender,sender_type,sender_id,ended_on,duration,time_run,...,response,response_action,prime,target,condition,soa_condition,congruence,correct_response,correctResponse,correct
0,51,1,NaN,NaN,Wecome1,canvas.Screen,1,timeout,499.56,3556.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,51,1,NaN,NaN,Wecome2,canvas.Screen,2,timeout,499.52,4056.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,51,1,NaN,NaN,Wecome3,canvas.Screen,3,timeout,499.52,4555.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,51,1,NaN,NaN,Instructions1,canvas.Screen,4,response,9061.10,5061.0,...,NaN,keypress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,51,1,NaN,NaN,Instructions 1a,canvas.Screen,5,response,2279.00,14148.0,...,NaN,keypress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,51,1,NaN,NaN,Instructions2,canvas.Screen,6,response,10717.24,16445.0,...,NaN,keypress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,51,1,NaN,NaN,Instructions3,canvas.Screen,7,response,2041.52,27166.0,...,NaN,keypress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,51,1,NaN,NaN,Instructions4,canvas.Screen,8,response,2045.32,29226.0,...,NaN,keypress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,51,1,NaN,NaN,Instructions5,canvas.Screen,9,response,1440.68,31284.0,...,NaN,keypress(Space),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,51,1,NaN,NaN,fixation,canvas.Screen,10_0_0,timeout,546.32,32746.0,...,NaN,NaN,snjghf,SHEEP,practice,practice,practice,n,NaN,NaN
10,51,1,NaN,NaN,mask1,canvas.Screen,10_0_1,timeout,49.94,33279.0,...,NaN,NaN,snjghf,SHEEP,practice,practice,practice,n,NaN,NaN
11,51,1,NaN,NaN,prime,canvas.Screen,10_0_2,timeout,49.96,33328.0,...,NaN,NaN,snjghf,SHEEP,practice,practice,practice,n,NaN,NaN
12,51,1,NaN,NaN,mask2,canvas.Screen,10_0_3,timeout,50.14,33379.0,...,NaN,NaN,snjghf,SHEEP,practice,practice,practice,n,NaN,NaN
13,51,1,NaN,NaN,target,canvas.Screen,10_0_4,response,843.38,33430.0,...,n,keypress(n),snjghf,SHEEP,practice,practice,practice,n,n,True
14,51,1,NaN,NaN,Practice Sequence,flow.Sequence,10_0,completion,1539.74,32746.0,...,NaN,NaN,snjghf,SHEEP,practice,practice,practice,n,NaN,NaN
15,51,1,NaN,NaN,fixation,canvas.Screen,10_1_0,timeout,539.38,34302.0,...,NaN,NaN,iweonf,BOAT,practice,practice,practice,m,NaN,NaN
16,51,1,NaN,NaN,mask1,canvas.Screen,10_1_1,timeout,49.96,34827.0,...,NaN,NaN,iweonf,BOAT,practice,practice,practice,m,NaN,NaN
17,51,1,NaN,NaN,prime,canvas.Screen,10_1_2,timeout,49.86,34878.0,...,NaN,NaN,iweonf,BOAT,practice,practice,practice,m,NaN,NaN
18,51,1,NaN,NaN,mask2,canvas.Screen,10_1_3,timeout,49.90,34928.0,...,NaN,NaN,iweonf,BOAT,practice,practice,practice,m,NaN,NaN
19,51,1,NaN,NaN,target,canvas.Screen,10_1_4,response,593.04,34977.0,...,m,keypress(m),iweonf,BOAT,practice,practice,practice,m,m,True

In [ ]:
# get list of column names for ease
list(raw)

['participant_id',
 'component_num',
 'url',
 'meta',
 'sender',
 'sender_type',
 'sender_id',
 'ended_on',
 'duration',
 'time_run',
 'time_render',
 'time_show',
 'time_end',
 'time_commit',
 'timestamp',
 'time_switch',
 'response',
 'response_action',
 'prime',
 'target',
 'condition',
 'soa_condition',
 'congruence',
 'correct_response',
 'correctResponse',
 'correct']

In [37]:
# make list of relevant columns
cols = ['participant_id', 'sender', 'duration', 'prime', 'target', 'response', 'condition', 'soa_condition', 'congruence', 'correct_response', 'correct']
cols

['participant_id',
 'sender',
 'duration',
 'prime',
 'target',
 'response',
 'condition',
 'soa_condition',
 'congruence',
 'correct_response',
 'correct']

In [50]:
# make new df with only relevant columns
df = raw[cols]
df

,participant_id,sender,duration,prime,target,response,condition,soa_condition,congruence,correct_response,correct
0,51,Wecome1,499.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,51,Wecome2,499.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,51,Wecome3,499.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,51,Instructions1,9061.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,51,Instructions 1a,2279.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
15632,69,Short Loop,85426.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15633,69,Break,868.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15634,69,Short Sequence,86318.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15635,69,Experiment Sequence,183618.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15636,69,root,216385.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
# keep only target rows i.e. filter out welcome screens etc
df = df[df['sender'] == 'target']
# df['sender'].unique()
# filter out practice rows
df = df[df['condition'] != 'practice']
# drop now-irrelevant sender column
df = df.drop(columns = ['sender'])
df

,participant_id,duration,prime,target,response,condition,soa_condition,congruence,correct_response,correct
40,51,520.14,roof,PIANO,m,Inc_Synth_Synth,long,incongruent,m,True
47,51,640.66,sheep,BULL,n,Inc_Nat_Nat,long,incongruent,m,False
54,51,597.74,fort,GOAT,n,Inc_Synth_Nat,long,incongruent,n,True
61,51,495.68,pear,PEAR,n,Con_Nat,long,congruent,n,True
68,51,556.86,olive,MOTOR,m,Inc_Nat_Synth,long,incongruent,m,True
...,...,...,...,...,...,...,...,...,...,...
15606,69,699.20,belt,BELT,m,Con_Synth,short,congruent,m,True
15612,69,580.20,daisy,DAISY,n,Con_Nat,short,congruent,n,True
15618,69,577.90,peach,SHED,m,Inc_Nat_Synth,short,incongruent,m,True
15624,69,661.10,rake,HUSKY,n,Inc_Synth_Nat,short,incongruent,n,True
15630,69,709.20,fern,PETAL,n,Inc_Nat_Nat,short,incongruent,n,True

In [52]:
# correct error
df.loc[df['target'] == 'BULL', 'correct_response'] = 'n'
#df['accuracy'] = df['response'] == df['correct_response']
df

,participant_id,duration,prime,target,response,condition,soa_condition,congruence,correct_response,correct
40,51,520.14,roof,PIANO,m,Inc_Synth_Synth,long,incongruent,m,True
47,51,640.66,sheep,BULL,n,Inc_Nat_Nat,long,incongruent,n,False
54,51,597.74,fort,GOAT,n,Inc_Synth_Nat,long,incongruent,n,True
61,51,495.68,pear,PEAR,n,Con_Nat,long,congruent,n,True
68,51,556.86,olive,MOTOR,m,Inc_Nat_Synth,long,incongruent,m,True
...,...,...,...,...,...,...,...,...,...,...
15606,69,699.20,belt,BELT,m,Con_Synth,short,congruent,m,True
15612,69,580.20,daisy,DAISY,n,Con_Nat,short,congruent,n,True
15618,69,577.90,peach,SHED,m,Inc_Nat_Synth,short,incongruent,m,True
15624,69,661.10,rake,HUSKY,n,Inc_Synth_Nat,short,incongruent,n,True
15630,69,709.20,fern,PETAL,n,Inc_Nat_Nat,short,incongruent,n,True

In [ ]:
df_grouped = df.groupby(['soa_condition', 'congruence']).mean(['duration'])
df_grouped

ValueError: numeric_only accepts only Boolean values

In [ ]:
df_grouped = df_grouped.reset_index()
df_grouped

NameError: name 'df_grouped' is not defined

In [ ]:
ax = sns.barplot(data = df_grouped, x = 'soa_condition', y = 'duration', hue = 'congruence')
# sns.move_legend(ax, "lower right")